GET http://localhost:5832/api/login/allUsers



POST http://localhost:5832/api/login/register
Content-Type: application/json

{
	"name": "sussy",
	"email": "sussy",
	"password": "bruh",
	"bookmarks": [],
	"recentRead": []
}
###

POST http://localhost:5832/api/login/login 
Content-Type: application/json

{
	"userName": "sussy",
	"password": "bruh"
}

###
POST http://localhost:5832/api/login/userInfo
Content-Type: application/json

{
	"accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3Vzc3kiLCJpYXQiOjE2NTU3NjYxNjksImV4cCI6MTY1NTc2Nzk2OX0.5OLnfu15-kSK2kgcUcMIwLMF9gPiOcYhW0sH-EPo1Qw",
	"recentRead" : ["The-Gamer-chapter-78-index-5","The-Gamer-chapter-79-index-5","The-Gamer-chapter-77-index-5","The-Gamer-chapter-76-index-5","The-Gamer-chapter-73-index-5","The-Gamer-chapter-75-index-5","The-Gamer-chapter-74-index-5","The-Gamer-chapter-71-index-5","The-Gamer-chapter-72-index-5","Onepunch-Man-chapter-164-index-2","Onepunch-Man-chapter-163-index-2","Onepunch-Man-chapter-161-index-2","Onepunch-Man-chapter-162-index-2","Onepunch-Man-chapter-160-index-2","Onepunch-Man-chapter-159-index-2"],
	"bookmarks": [{"seriesName":"Jujutsu Kaisen","indexName":"Jujutsu-Kaisen"},{"seriesName":"The Gamer","indexName":"The-Gamer"},{"seriesName":"My Hero Academia","indexName":"Boku-No-Hero-Academia"},{"seriesName":"Omniscient Reader","indexName":"Omniscient-Readers-Viewpoint"},{"seriesName":"The Way of the Househusband","indexName":"Gokushufudou-The-Way-Of-The-House-Husband"}]
}

### 
POST http://localhost:5832/api/login/newAccessToken
Content-Type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3Vzc3kiLCJpYXQiOjE2NTU3NjYwMzgsImV4cCI6MTY1ODM1ODAzOH0.4z4XstLwPT2LXcSXfNSGukvdDqU2_Sh54e7pPeF5gm4"
}