name: Trigger auto deployment for magma-manga-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/magma-manga-test-AutoDeployTrigger-a05bcb1d-9644-49ee-9ee4-f835dc16c874.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MAGMAMANGATEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MAGMAMANGATEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MAGMAMANGATEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.MAGMAMANGATEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MAGMAMANGATEST_REGISTRY_PASSWORD }}
          containerAppName: magma-manga-test
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


